# Task Service Configuration
server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
      notificationService:
        register-health-indicator: true
        sliding-window-size: 5
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50

  timelimiter:
    instances:
      userService:
        timeout-duration: 3s
      notificationService:
        timeout-duration: 2s

logging:
  level:
    com.example.taskservice: DEBUG
    io.github.resilience4j: DEBUG
